Repository VKCOM/kphpstorm, pull requests merged in 2022-08, with the labels that each got.

#31 fixed a link to `Actions` in the readme
  README.md
Labels: small fix

#30 version 1.2.6 for PhpStorm 2022.2
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/kotlin/com/vk/kphpstorm/exphptype/PhpTypeToExPhpTypeParsing.kt
  src/main/kotlin/com/vk/kphpstorm/exphptype/psi/CustomVarParamReturnDocTags.kt
  src/main/kotlin/com/vk/kphpstorm/typeProviders/TupleShapeTypeProvider.kt
  src/test/fixtures/kphp_type/array_force.good.fixture.php
  src/test/fixtures/strict_typing/foreach_argument.fixture.php
  src/test/fixtures/strict_typing/indexing_expression.fixture.php
  src/test/kotlin/com/vk/kphpstorm/testing/tests/KphpTypeTest.kt
Labels: enhancement

#33 overriding the warning level of standard inspections
  src/main/kotlin/com/vk/kphpstorm/configuration/KphpStormAutoSetup.kt
  src/test/fixtures/native_inspection/case_sensitive.fail.fixture.php
  src/test/kotlin/com/vk/kphpstorm/testing/infrastructure/InspectionTestBase.kt
  src/test/kotlin/com/vk/kphpstorm/testing/tests/NativeInspectionTest.kt
Labels: enhancement

#34 added changelog
  CHANGELOG.md
Labels: documentation
