Repository VKCOM/kphpstorm, pull requests merged in 2022-07, with the labels that each got.

#21 force type int for `count()`
  src/main/kotlin/com/vk/kphpstorm/typeProviders/FunctionsTypeProvider.kt
Labels: small fix

#26 added support @kphp-json tag
  src/main/kotlin/com/vk/kphpstorm/KphpStormParserDefinition.kt
  src/main/kotlin/com/vk/kphpstorm/completion/KphpJsonAttributeCompletionProvider.kt
  src/main/kotlin/com/vk/kphpstorm/completion/KphpStormCompletionContributor.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/AllKphpdocTagsList.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/KphpDocTag.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/KphpJsonTag.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/psi/KphpDocElementTypes.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/psi/KphpDocJsonAttributePsiImpl.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/psi/KphpDocJsonForEncoderPsiImpl.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/psi/KphpDocTagJsonElementType.kt
  src/main/kotlin/com/vk/kphpstorm/kphptags/psi/KphpDocTagJsonPsiImpl.kt
  src/main/kotlin/com/vk/kphpstorm/typeProviders/JsonEncoderTypeProvider.kt
  src/main/resources/META-INF/plugin.xml
  src/test/fixtures/kphp_type/json_tag.good.fixture.php
  src/test/fixtures/kphpdoc_inspection/json_tag.fail_1.fixture.php
  src/test/fixtures/kphpdoc_inspection/json_tag.fail_2.fixture.php
  src/test/fixtures/kphpdoc_inspection/json_tag.good_1.fixture.php
  src/test/fixtures/kphpdoc_inspection/json_tag.good_2.fixture.php
  src/test/kotlin/com/vk/kphpstorm/testing/tests/KphpDocInspectionTest.kt
  src/test/kotlin/com/vk/kphpstorm/testing/tests/KphpTypeTest.kt
Labels: enhancement

#28 version 1.2.5
  CHANGELOG.md
  build.gradle.kts
  gradle.properties
Labels: documentation
