Repository VKCOM/kphpstorm, pull requests merged in 2022-06, with the labels that each got.

#4 Update project
  .gitignore
  .run/Run IDE with Plugin.run.xml
  .run/Run Plugin Tests.run.xml
  .run/Run Plugin Verification.run.xml
  CHANGELOG.md
  LICENSE
  build.gradle
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  settings.gradle.kts
Labels: refactoring

#13 added GitHub Actions
  .github/workflows/build.yml
Labels: enhancement

#18 fixed PHP 7.4 version for tests by default
  src/test/fixtures/strict_typing/return_mismatch.fixture.php
  src/test/fixtures/strict_typing/return_statement_1.fixture.php
  src/test/fixtures/strict_typing/return_statement_8.fixture.php
  src/test/kotlin/com/vk/kphpstorm/testing/infrastructure/InspectionTestBase.kt
  src/test/kotlin/com/vk/kphpstorm/testing/infrastructure/IntentionTestBase.kt
Labels: enhancement

#12 fixed `props_assignments_10.fixture.php` test fail
  src/test/fixtures/strict_typing/props_assignments_10.fixture.php
Labels: bug

#17 added a logo to tools menu
  src/main/resources/META-INF/plugin.xml
  src/main/resources/icons/kphp_logo.svg
  src/main/resources/icons/kphp_logo_dark.svg
Labels: enhancement

#23 added tests for ffi types
  src/test/fixtures/kphp_type/ffi_tag.good.fixture.php
  src/test/kotlin/com/vk/kphpstorm/testing/tests/KphpTypeTest.kt
  src/test/kotlin/com/vk/kphpstorm/testing/tests/KphpUnsupportedFunctionCallInspectionTest.kt
Labels: refactoring
